version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=dvp_task;User=sa;Password=dvpTask123$;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - appnetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=dvpTask123$
      - MSSQL_PID=Express
      - MSSQL_DB=dvp_task
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - appnetwork
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P dvpTask123$ -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  appnetwork:
    driver: bridge

volumes:
  sqlserverdata:
